# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  JDK_VERSION: 21
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: '1'
          clean: 'true'

      - name: Build with Gradle
        run: gradle build

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish client to GitHub Packages
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
