# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - 'docs/**'


concurrency:
  group: ${{ github.workflow }}-push-to-main
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

env:
  JDK_VERSION: 21
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '${{ env.JDK_VERSION }}'
          cache: 'gradle'

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish client to GitHub Packages
        run: ./gradlew final printFinalReleaseNote --parallel
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md cors/README.md json/README.md jwt/README.md metrics/README.md openapi/README.md swagger-ui/README.md tracing/README.md typesafe/README.md

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: "${{ github.actor }}"
          committer_email: "${{ github.actor }}@users.noreply.github.com"
          add: .
          message: 'Update version in README files'
