name: verify
on:
  pull_request:
    paths-ignore:
      - README.md
      - '**/README.md'
      - 'docs/**'

env:
  JDK_VERSION: 21
  GRADLE_OPTS: -Dorg.gradle.daemon=false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build and Run Tests
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      checks: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '${{ env.JDK_VERSION }}'
          cache: 'gradle'
      - name: Build and Run Tests
        run: ./gradlew test koverXmlReport --parallel
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish Kover Report
        uses: madrapps/jacoco-report@v1.7.1
        if: success() || failure() # always run even if the previous step fails
        with:
          paths: |
            ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 60
      - name: Coverage verify
        run: ./gradlew koverVerify --parallel
      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
#      - name: Publish client to GitHub Packages
#        run: ./gradlew devSnapshot printDevSnapshotReleaseNote
#        env:
#          GITHUB_ACTOR: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      checks: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '${{ env.JDK_VERSION }}'
          cache: 'gradle'
      - name: Run Detekt
        run: ./gradlew detekt
      - name: Publish Detekt Report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        if: success() || failure() # always run even if the previous step fails
        with:
          path: 'build/reports/detekt/merge.xml'
